// Centralized icon barrel mapping Phosphor-style names to react-icons (Phosphor set)
// This preserves existing component names used across the codebase while sourcing icons from react-icons/pi.

export {
	// Common UI/status icons
	PiCheckCircle as CheckCircle,
	PiXCircle as XCircle,
	PiWarning as Warning,
	PiWarningCircle as WarningCircle,
	PiClock as Clock,
	PiCalendar as Calendar,
	PiUsers as Users,
	PiPhone as Phone,
	PiEnvelope as Envelope,
	PiEnvelopeSimple as EnvelopeSimple,
	PiTrash as Trash,
	PiStar as Star,
	PiGear as Gear,
	PiGearSix as GearSix,
	PiEye as Eye,
	PiArrowsClockwise as ArrowsClockwise,
	PiWaveTriangle as WaveTriangle,
	PiTrendUp as TrendUp,
	PiArrowLeft as ArrowLeft,
		PiArrowRight as ArrowRight,
	// Category Navigation specific icons
	PiChefHat as ChefHat,
	PiWine as Wine,
	PiHeart as Heart,
	PiSparkle as Sparkle,
	PiMapPin as MapPin,
	PiCalendarCheck as CalendarCheck,
	PiChatCircle as ChatCircle,
	PiCoffee as Coffee,
	PiBeerBottle as BeerBottle,
	PiDrop as Drop,
	PiForkKnife as ForkKnife,
	PiMartini as Martini,
	PiTruck as Truck,
	PiStorefront as Storefront,
	PiBookOpen as BookOpen,
	PiClockClockwise as ClockClockwise,
		// Additional icons used elsewhere
		PiGlobe as Globe,
		PiCaretDown as CaretDown,
		PiCaretLeft as CaretLeft,
		PiCaretRight as CaretRight,
		PiHouse as House,
		PiMagnifyingGlass as MagnifyingGlass,
		PiX as X,
		PiList as List,
		PiInstagramLogo as InstagramLogo,
		PiFacebookLogo as FacebookLogo,
		PiPencilSimple as PencilSimple,
		PiArrowUpRight as ArrowUpRight,
		PiArrowClockwise as ArrowClockwise,
} from 'react-icons/pi';

