// Centralized icon barrel mapping Phosphor-style names to react-icons (Phosphor set)
// This preserves existing component names used across the codebase while sourcing icons from react-icons/pi.

export {
	// Common UI/status icons
	PiCheckCircle as CheckCircle,
	PiXCircle as XCircle,
	PiX as X,
	PiWarning as Warning,
	PiWarningCircle as WarningCircle,
	PiClock as Clock,
	PiCalendar as Calendar,
	PiUsers as Users,
	PiPhone as Phone,
	PiEnvelope as Envelope,
	PiEnvelopeSimple as EnvelopeSimple,
	PiTrash as Trash,
	PiStar as Star,
	PiGear as Gear,
	PiGearSix as GearSix,
	PiEye as Eye,
	PiArrowsClockwise as ArrowsClockwise,
	PiArrowClockwise as ArrowClockwise,
	PiWaveTriangle as WaveTriangle,
	PiTrendUp as TrendUp,
	// Navigation and layout
	PiCaretLeft as CaretLeft,
	PiCaretRight as CaretRight,
	PiCaretDown as CaretDown,
	PiHouse as House,
	PiArrowLeft as ArrowLeft,
	PiArrowRight as ArrowRight,
	PiArrowUpRight as ArrowUpRight,
	// Domain-specific icons
	PiChefHat as ChefHat,
	PiWine as Wine,
	PiHeart as Heart,
	PiSparkle as Sparkle,
	PiMapPin as MapPin,
	PiCalendarCheck as CalendarCheck,
	PiChatCircle as ChatCircle,
	PiCoffee as Coffee,
	PiBeerBottle as BeerBottle,
	PiDrop as Drop,
	PiForkKnife as ForkKnife,
	PiGlobe as Globe,
	PiMagnifyingGlass as MagnifyingGlass,
	PiPencilSimple as PencilSimple,
	PiMartini as Martini,
	PiTruck as Truck,
	PiStorefront as Storefront,
	PiBookOpen as BookOpen,
	PiClockClockwise as ClockClockwise,
	PiList as List,
	PiInstagramLogo as InstagramLogo,
	PiFacebookLogo as FacebookLogo,
} from 'react-icons/pi';

