name: "Security Scan (Free Alternative)"

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    schedule:
        # Run every Monday at 6:00 AM UTC
        - cron: "0 6 * * 1"

permissions:
    contents: read
    security-events: write
    actions: read

jobs:
    eslint-security:
        name: ESLint Security Analysis
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint with security plugins
              run: npm run lint
              continue-on-error: true

    npm-audit:
        name: NPM Security Audit
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run npm audit
              run: npm audit --audit-level=moderate
              continue-on-error: true

            - name: Run npm audit fix (dry-run)
              run: npm audit fix --dry-run
              continue-on-error: true

    snyk-scan:
        name: Snyk Security Scan (Free Tier)
        runs-on: ubuntu-latest
        # Snyk offers free scanning for open source projects
        # You can sign up at https://snyk.io and add SNYK_TOKEN to secrets
        # Remove 'if: false' when you have a Snyk token
        if: false

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@master
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  args: --severity-threshold=high

    trivy-scan:
        name: Trivy Security Scanner
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run Trivy vulnerability scanner in fs mode
              uses: aquasecurity/trivy-action@master
              with:
                  scan-type: "fs"
                  scan-ref: "."
                  format: "sarif"
                  output: "trivy-results.sarif"
                  severity: "CRITICAL,HIGH,MEDIUM"

            - name: Upload Trivy results to GitHub Security
              uses: github/codeql-action/upload-sarif@v3
              if: always()
              with:
                  sarif_file: "trivy-results.sarif"
                  category: "trivy-fs"

    secret-scanning:
        name: Secret Scanning (Gitleaks)
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Run Gitleaks
              uses: gitleaks/gitleaks-action@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
